###
# GET NEW ACCESS TOKEN USING REFRESHTOKEN
POST http://localhost:1337/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGFiM2Q4YTdmODlhMTgzYjU2ZTJjZCIsInVzZXJuYW1lIjoibWkiLCJpYXQiOjE2MzY1NDQ4MzN9.6-cgGzLxbn4jd6OlwC57uzTwF1bBbE619IdfXjXeKcA"
}

###
# SEE SECRET CONTENT USING TOKEN
GET http://localhost:1337/demo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGJhZGYyYzkzZDBkMTc5YWYzMzFiZiIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MzY1NDQxMjEsImV4cCI6MTYzNjU0NDE1MX0.w5hRY7bDDWeiNoMpCGN7oSazBRqTFaJD5kovAvVbthI


###
# DELETE TOKEN / logout
DELETE http://localhost:1337/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWkiLCJpYXQiOjE2MzYzODEyOTR9.cgS-Iil0cOw243QnjUtaS4rmoDrCXVPEoGOqw93EeGE"
}

###
# CREATE USER MI
POST http://localhost:1337/register
Content-Type: application/json

{
    "username": "admin",
    "password": "123"
}

###
# GET USERS LIST
// GET http://localhost:1337/users

###
# LOGIN USER MI
POST http://localhost:1337/login
Content-Type: application/json

{
    "username": "mi",
    "password": "123"
}
