###
# 2: GET NEW ACCESS TOKEN USING REFRESHTOKEN
POST http://localhost:1337/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWkiLCJpYXQiOjE2MzY0NzE4NTZ9.Rj32wDd7uJzLnwp7fv-gUMC3L42AzD3SmFn8cN6E9dA"
}

###
# 3: SEE SECRET CONTENT USING TOKEN
GET http://localhost:1337/demo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWkiLCJpYXQiOjE2MzY0NzI1MzIsImV4cCI6MTYzNjQ3MjU2Mn0.OA8CJs3dzyqo4ykTBE7TUXEHVQe4BBUXWUzo3jsJ7JQ


###
# 4: DELETE TOKEN / logout
DELETE http://localhost:1337/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibWkiLCJpYXQiOjE2MzYzODEyOTR9.cgS-Iil0cOw243QnjUtaS4rmoDrCXVPEoGOqw93EeGE"
}

###
# 5: CREATE USER MI
POST http://localhost:1337/register
Content-Type: application/json

{
    "name": "mi",
    "password": "123"
}

###
# 6: GET USERS LIST
GET http://localhost:1337/users

###
# 7: LOGIN USER MI
POST http://localhost:1337/login
Content-Type: application/json

{
    "name": "mi",
    "password": "123"
}
